# Generated by Django 5.0.2 on 2024-03-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_icon',
            field=models.ImageField(default='images/jasoos.svg', upload_to='tools_icon', verbose_name='Icon'),
        ),
    ]
